### ISSUE TITLE
mvn tomcat7:run will not start application

### ISSUE THREAD

**Issue by mireczatko** [AxonFramework/Axon-trader#23]
after clone master branch and launching mvn tomcat7:run

`java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]`
...
`Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsSci cannot be cast to javax.servlet.ServletContainerInitializer
        at org.apache.catalina.startup.ContextConfig.getServletContainerInitializer(ContextConfig.java:1670)
        at org.apache.catalina.startup.ContextConfig.getServletContainerInitializers(ContextConfig.java:1652)
        at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1562)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1270)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:376)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 6 more`

**Comment by mengjiann** [comment]
I think it is caused by the following:

**Comment by mengjiann** [comment]
Hi mireczatko, 

I managed to get this working. I noticed that maven will use embedded tomcat 7.0.47 as default when you launch the webapp by using tomcat7:run. Thus, you need to specify the tomcat version for tomcat7-maven-plugin by referring: http://tomcat.apache.org/maven-plugin-trunk/tomcat7-maven-plugin/adjust-embedded-tomcat-version.html

Because the project is configured to compile using java version 1.8 in axon-trader pom.file. Therefore, you will have to change it to java 1.7. 

Besides that, module axon-trader-webui will include dependency tomcat-embed-websocket version 8. You will have to exclude it as below:
 <dependency>
            <groupId>org.axonframework.samples</groupId>
            <artifactId>axon-trader-infrastructure</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.tomcat.embed</groupId>
                    <artifactId>tomcat-embed-websocket</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

I hope it helps you to run the trader example :)

**Comment by mireczatko** [comment]
Thank you very much, @mengjiann. Excluding  tomcat-embed-websocket solved the issue.
