### ISSUE TITLE
Error creating bean with name 'companyOrderBookListener' 

### ISSUE THREAD

**Issue by huiwenhan** [AxonFramework/Axon-trader#29]
ERROR - tartStop-1 - ContextLoader              - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'companyOrderBookListener' defined in file [D:\project\Axon-trader\companies\target\classes\org\axonframework\samples\trader\company\command\CompanyOrderBookListener.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.axonframework.samples.trader.company.command.CompanyOrderBookListener]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.axonframework.samples.trader.company.command.CompanyOrderBookListener.<init>()
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1076)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1021)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.axonframework.samples.trader.company.command.CompanyOrderBookListener]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.axonframework.samples.trader.company.command.CompanyOrderBookListener.<init>()
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1069)
        ... 22 more
Caused by: java.lang.NoSuchMethodException: org.axonframework.samples.trader.company.command.CompanyOrderBookListener.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
        ... 23 more

**Comment by daniel-smith** [comment]
This commit seems to have removed the default constructor - https://github.com/AxonFramework/Axon-trader/commit/7982724715dae69d776e9c9db2258577c8664b0a

**Comment by smcvb** [comment]
@huiwenhan sorry, but we're quite rigorously adjusting the whole wiring process of this application and was forced to to a push at some point.
I'd expect the master branch to be broken now, but this should be fixed in the next couple of days.

Sorry for the inconvenience, I'll keep you posted.

**Comment by vskiadas90** [comment]
@smcvb  Sorry but what do you mean you where forced to push at some point? Haven't you heard of branches? Unless pointed otherwise, usually the norm is that master branch is up-to-date, and with appropriate instructions from the readme file, one should be able to easily run the application. 
  And in one of the main axon-provided examples of how to do several things, the master branch is simply broken.

**Comment by smcvb** [comment]
Although I fully agree with your stance @vskiadas90, this is the route we've currently taken.

As soon as this changes, one way or another, we'll update this ticket appropriately.

Again, I am very sorry for the inconvenience.

**Comment by smcvb** [comment]
I've adjusted the `README.md` to clarify the current state of the application somewhat.

**Comment by vskiadas90** [comment]
@smcvb Very good.

**Comment by lqbilbo** [comment]
#CompanyOrderBookListener.java
@Autowired
    public CompanyOrderBookListener(CommandGateway commandGateway) {
        this.commandGateway = commandGateway;
    }

I have fixed the bug just by adding the annotation Autowired. @smcvb

**Comment by smcvb** [comment]
Sorry for the hold up guys.
I've just went through the effort to pull this application out of limbo into a workings state.

As it stands now, the `master` branch works as described in the `README.md`.
Thus, `mvn clean install` doesn't throw any exceptions, and `mvn tomcat7:run` actually runs the application.

As far as I can see, all the operation from the front-end also work as expected.
If you find anything which is out of the ordinary, feel free to open a new issues.

For now I'll assume this issue is resolved because of the aforementioned actions I've taken.
If this issue still occurs, feel free to comment further on this issue.

Thanks for the patience on this matter, it's much appreciated!
