### ISSUE TITLE
query.users.UserEventHandler - No default constructor found

### ISSUE THREAD

**Issue by JohT** [AxonFramework/Axon-trader#30]
I downloaded the axon-trader demo today. When i run mvn tomcat7:run in the main folder, i get this error message:

INFORMATION: Initializing Spring root WebApplicationContext
ERROR - tartStop-1 - ContextLoader              - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userEventHandler' defined in file [/Users/skipped/Downloads/Engineering/Java/AxonFramework/Demo/axon-trade/users-query/target/classes/org/axonframework/samples/trader/query/users/UserEventHandler.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.axonframework.samples.trader.query.users.UserEventHandler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.axonframework.samples.trader.query.users.UserEventHandler.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1076)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1021)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.axonframework.samples.trader.query.users.UserEventHandler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.axonframework.samples.trader.query.users.UserEventHandler.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1069)
	... 22 more
Caused by: java.lang.NoSuchMethodException: org.axonframework.samples.trader.query.users.UserEventHandler.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	... 23 more
Jul 17, 2018 8:39:59 PM org.apache.catalina.core.StandardContext listenerStart

**Comment by JohT** [comment]
I've used the master branch and unzipped it on my mac.

**Comment by ranajit-jana** [comment]
Thank you. Is the fixes available on the master branch?  when i take the latest i am still getting the following error

```
ERROR - tartStop-1 - ContextLoader              - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'portfolioManagementUserListener' defined in file [/home/ranajit/microservices/saga/Axon-trader/orders/target/classes/org/axonframework/samples/trader/orders/command/PortfolioManagementUserListener.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.axonframework.samples.trader.orders.command.PortfolioManagementUserListener]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.axonframework.samples.trader.orders.command.PortfolioManagementUserListener.<init>()

```

**Comment by ranajit-jana** [comment]
i took the latest from /lqbilbo/Axon-trader

I am getting a error as below.

```


ERROR - tartStop-1 - ContextLoader              - Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hsqlDBInit' defined in file [/home/ranajit/microservices/saga/Axon-trader/web-ui/target/classes/org/axonframework/samples/trader/webui/init/HsqlDBInit.class]: Unsatisfied dependency expressed through constructor argument with index 14 of type [org.axonframework.samples.trader.query.users.UserCommandHandler]: : Error creating bean with name 'userCommandHandler' defined in file [/home/ranajit/microservices/saga/Axon-trader/users-query/target/classes/org/axonframework/samples/trader/query/users/UserCommandHandler.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.axonframework.samples.trader.query.users.UserCommandHandler]: Constructor threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userCommandHandler' defined in file [/home/ranajit/microservices/saga/Axon-trader/users-query/target/classes/org/axonframework/samples/trader/query/users/UserCommandHandler.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.axonframework.samples.trader.query.users.UserCommandHandler]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:747)
```

**Comment by lqbilbo** [comment]
@ranajit-jana Yes,I fixed the bug on the master branch.
And I took over my commits on that day, I found I put the UserCommandHandler into the HsqlDBInit construtor which make it be useful.
Have a try again?

**Comment by smcvb** [comment]
Sorry for the hold up guys.
I've just went through an effort to change the current state into a working state.

As it stands now, the `master` branch works as described in the `README.md`.
Thus, `mvn clean install` doesn't throw any exceptions, and `mvn tomcat7:run` actually runs the application.

As far as I can see, all the operation from the front-end also work as expected.
If you find anything which is out of the ordinary, feel free to open a new issues.

For now I'll assume this issue is resolve because of the aforementioned actions I've taken.
Thanks for the patience on this matter, it's much appreciated!
